'use strict';
const DEFAULTS={base:8,background:6,t:8,b:6,d:2,tb:2,td:1,bd:1,tbd:1,natural:10,human:14,hazardFactor:1,solidarity:4};
const DEFINITIONS=[['base','Base risk',0,20],['background','Background contribution',0,15],['t','Trauma vulnerability',-5,20],['b','Cognitive bias',-5,20],['d','Dissonance',-10,10],['tb','Trauma × bias',-5,10],['td','Trauma × dissonance',-5,10],['bd','Bias × dissonance',-5,10],['tbd','Three-factor interaction',-5,10],['natural','Natural disaster',0,25],['human','Human-caused disaster',0,25],['hazardFactor','Disaster × each factor',-5,10],['solidarity','Solidarity protection',0,15]];
const $=id=>document.getElementById(id);
let coeff={...DEFAULTS};
const sliders=$('sliders');
for(const [key,label,min,max] of DEFINITIONS){const row=document.createElement('div');row.className='slider-row';const top=document.createElement('div');top.className='slider-top';const caption=document.createElement('label');caption.htmlFor='range-'+key;caption.textContent=label;const output=document.createElement('output');output.id='out-'+key;top.append(caption,output);const input=document.createElement('input');input.type='range';input.id='range-'+key;input.min=min;input.max=max;input.step='.5';input.value=coeff[key];input.addEventListener('input',()=>{coeff[key]=Number(input.value);render()});row.append(top,input);sliders.append(row)}
function risk(t,b,d,h,s){const c=coeff;let r=c.base+.35*c.background+c.t*t+c.b*b+c.d*d+c.tb*t*b+c.td*t*d+c.bd*b*d+c.tbd*t*b*d;if(h){r+=h===1?c.natural:c.human;r+=c.hazardFactor*(t+b+d);if(s)r-=c.solidarity}return Math.max(0,Math.min(100,r))}
function render(){const t=+$('tOn').checked,b=+$('bOn').checked,d=+$('dOn').checked,h=+$('hazard').value,s=+$('sOn').checked;const ref=risk(0,0,0,0,0),selected=risk(t,b,d,h,s),delta=selected-ref;$('baselineMetric').textContent=ref.toFixed(1)+'%';$('selectedMetric').textContent=selected.toFixed(1)+'%';$('deltaMetric').textContent=(delta>=0?'+':'')+delta.toFixed(1)+' pp';$('selectedCaption').textContent=[['Ordinary','Natural disaster','Human-caused disaster'][h],s&&h?'solidarity active':null].filter(Boolean).join(' · ');$('sOn').disabled=!h;document.querySelector('.solidarity').classList.toggle('disabled',!h);
 for(const [key] of DEFINITIONS)$('out-'+key).textContent=(coeff[key]>=0?'+':'')+coeff[key].toFixed(1);
 const rows=[['Reference',ref,''],['Trauma only',risk(1,0,0,0,0),''],['Bias only',risk(0,1,0,0,0),''],['Dissonance only',risk(0,0,1,0,0),''],['All three',risk(1,1,1,0,0),'all'],['Selected',selected,'selected']];const bars=$('bars');bars.replaceChildren();for(const [label,value,cls] of rows){const row=document.createElement('div');row.className='bar-row '+cls;const name=document.createElement('span');name.textContent=label;const track=document.createElement('div');track.className='bar-track';const fill=document.createElement('div');fill.className='bar-fill';fill.style.width=Math.min(100,value/60*100)+'%';track.append(fill);const num=document.createElement('strong');num.textContent=value.toFixed(1)+'%';row.append(name,track,num);bars.append(row)}bars.setAttribute('aria-label',rows.map(x=>x[0]+' '+x[1].toFixed(1)+' percent').join('; '));$('formulaText').textContent=`Risk = ${coeff.base} + 0.35 × ${coeff.background} + ${coeff.t}T + ${coeff.b}B + ${coeff.d}D + ${coeff.tb}TB + ${coeff.td}TD + ${coeff.bd}BD + ${coeff.tbd}TBD + disaster terms − solidarity.`}
for(const id of ['tOn','bOn','dOn','sOn','hazard'])$(id).addEventListener('change',render);
$('reset').addEventListener('click',()=>{coeff={...DEFAULTS};for(const [key] of DEFINITIONS)$('range-'+key).value=coeff[key];$('tOn').checked=$('bOn').checked=$('dOn').checked=true;$('sOn').checked=false;$('hazard').value='0';render()});render();
